"""add conversation_sessions and conversation_messages

Revision ID: b2a4d6f3e9c8
Revises: 8c0d4e6f2a9b
Create Date: 2026-05-31 16:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2a4d6f3e9c8"
down_revision: str | None = "8c0d4e6f2a9b"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic ###
    op.create_table(
        "conversation_sessions",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("title", sa.String(255), nullable=False, server_default="新对话"),
        sa.Column(
            "metadata",
            sa.JSON(),
            nullable=True,
            comment="会话上下文: current_candidate_id, last_intent, etc.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conv_session_user", "conversation_sessions", ["user_id", "updated_at"]
    )

    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("session_id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("role", sa.String(16), nullable=False, comment="user | assistant | system | tool"),
        sa.Column("content", sa.Text(), nullable=False, server_default=""),
        sa.Column(
            "tool_calls",
            sa.JSON(),
            nullable=True,
            comment="assistant 消息的工具调用列表 (OpenAI 格式)",
        ),
        sa.Column(
            "tool_result",
            sa.JSON(),
            nullable=True,
            comment="tool 消息的执行结果",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["session_id"], ["conversation_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conv_msg_session_created",
        "conversation_messages",
        ["session_id", "created_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("conversation_messages")
    op.drop_table("conversation_sessions")
