"""add screening status

Revision ID: fe85e4504f2b
Revises: 4d3216fe7ec2
Create Date: 2026-05-25 18:07:14.273560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe85e4504f2b'
down_revision: Union[str, Sequence[str], None] = '4d3216fe7ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)

    # Add new enum values for candidate screening status
    op.execute("ALTER TYPE candidate_status ADD VALUE IF NOT EXISTS 'pending_eval'")
    op.execute("ALTER TYPE candidate_status ADD VALUE IF NOT EXISTS 'evaluating'")
    op.execute("ALTER TYPE candidate_status ADD VALUE IF NOT EXISTS 'evaluated'")
    op.execute("ALTER TYPE candidate_status ADD VALUE IF NOT EXISTS 'in_interview'")
    op.execute("ALTER TYPE candidate_status ADD VALUE IF NOT EXISTS 'completed'")
    op.execute("ALTER TYPE candidate_status ADD VALUE IF NOT EXISTS 'failed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')

    # Note: PostgreSQL does not support removing values from an enum type.
    # To fully downgrade, you would need to create a new type and migrate.
    # ### end Alembic commands ###
